#! /usr/bin/env bash
# Copyright (c) 2021 Rebecca Taylor - MIT License
MICROTAP_VERSION=1.9.2; [ "$1" = --version ] && { echo "microtap version $MICROTAP_VERSION"; exit 0; }
[ "$1" = --list ] && [ -f "$2" ] && { source "$2"; if declare -pF | awk '{print $3}' | grep -i '^test\|^spec' 2>/dev/null; then exit 0; else exit $?; fi; }
runAll() { if [ -z "${1:-}" ]; then return 0; fi; if __spec__functions="$( declare -pF | awk '{print $3}' | grep -i "$1" 2>/dev/null )"; then for __spec__fn in $__spec__functions; do $__spec__fn; done; fi; }
recordCmd() { spec_return=$?; if (( $1 == 0 )) && [ "$2" != "$0" ] && { [ -z "${__spec__sourcedOk:-}" ] || [ "$4" = "$SPEC_TEST" ]; } && [ -z "${__spec__testDone:-}" ]; then CMD_INFO=("${@:1}"); fi; if [ "$4" = "${CMD_INFO[3]:-}" ]; then return $spec_return; else return 0; fi; }
[ "$1" = --run ] && [ -f "$2" ] && [ -n "$3" ] && { SPEC_FILE="$2"; SPEC_TEST="$3"; shift 3; set -eET; trap 'spec_return=$?; [ -z "${__spec__sourcedOk:-}" ] && declare -p CMD_INFO; exit $spec_return;' ERR
  trap 'CMD_INFO[0]=$?; __spec__testDone=true; [ "${__spec__sourcedOk:-}" = true ] && runAll "^teardown\|^after"; declare -p CMD_INFO' EXIT
  trap 'recordCmd $? "${BASH_SOURCE[0]}" "$LINENO" "${FUNCNAME[0]:-}" "$BASH_COMMAND";' DEBUG; 
  source "$SPEC_FILE"; __spec__sourcedOk=true; runAll "^setup\|^before"; "$SPEC_TEST"; exit $?; }; SPEC_FILES=()
while (( $# > 0 )); do [ "$1" = -f ] || [ "$1" = --filter ] && { SPEC_FILTER="$2"; shift 2; continue; } || { [ -f "$1" ] && _="$( source "$1" 2>&1 )" && SPEC_FILES+=("$1"); shift; }; done
declare -i TEST_COUNT=0; for SPEC_FILE in "${SPEC_FILES[@]}"; do __spec__testCount="$("$0" --list "$SPEC_FILE" 2>/dev/null | grep -i "${SPEC_FILTER:-.}" | wc -l)"; (( TEST_COUNT += __spec__testCount )); done
declare -i PASSED=0; declare -i FAILED=0; declare -i TEST_NUMBER=0; (( TEST_COUNT > 0 )) && echo "1..$TEST_COUNT" || exit 0
for SPEC_FILE in "${SPEC_FILES[@]}"; do
  if [ -f "$SPEC_FILE" ]; then
    for SPEC_TEST in $("$0" --list "$SPEC_FILE" 2>/dev/null | grep -i "${SPEC_FILTER:-.}" ); do (( TEST_NUMBER++ ))
      SPEC_TEST_OUTPUT="$({ STDERR="$({ STDOUT="$( "$0" --run "$SPEC_FILE" "$SPEC_TEST" )"; } 2>&1; declare -i EXITCODE=$?; declare -p STDOUT >&2; declare -p EXITCODE >&2; exit $EXITCODE;)"; declare -p STDERR; exit 0; } 2>&1 )"
      eval "$SPEC_TEST_OUTPUT";
      [[ "$STDOUT" =~ .*(declare[[:space:]]-a[[:space:]]CMD_INFO=[\']?\(.*)$ ]] && __spec_lastCmdText__="${BASH_REMATCH[1]}"
      [ -n "$__spec_lastCmdText__" ] && { eval "$__spec_lastCmdText__"; STDOUT="${STDOUT%"$__spec_lastCmdText__"}"; STDOUT="${STDOUT%$'\n'}"; }
      (( EXITCODE == 0 )) && { (( PASSED++ )); echo "ok $TEST_NUMBER - $SPEC_TEST"; } || { (( FAILED++ )); echo "not ok $TEST_NUMBER - $SPEC_TEST"; }
      (( EXITCODE != 0 )) || [ "${VERBOSE:-}" = true ] && {
        [ -n "$STDOUT" ] && { echo "# Standard Output:"; echo "$( echo "$STDOUT" | sed 's/^/#  /' )"; }
        [ -n "$STDERR" ] && { echo "# Standard Error:"; echo "$( echo "$STDERR" | sed 's/^/#  /' )"; }
        (( ${#CMD_INFO[@]} > 2 )) && { (( EXITCODE != 0 )) || [ "$STACKTRACE" = true ]; } && {
          echo "# Stacktrace:"; [ -f "${CMD_INFO[1]}" ] && [ "${CMD_INFO[2]}" -le "$( wc -l < "${CMD_INFO[1]}" 2>&1 )" ] && {
            echo "#   ${CMD_INFO[1]}:${CMD_INFO[2]} ${CMD_INFO[3]}"; echo "$( sed "${CMD_INFO[2]}q;d" "${CMD_INFO[1]}" | sed "s/^ *//g" | sed "s/^/#     /" )"; } || {
            echo "#   ${CMD_INFO[3]}"; echo "#     ${CMD_INFO[4]}"; }; }; }
    done
  fi
done; (( FAILED > 0 )) && exit 1 || exit 0