source "https://rubygems.org"

# Security updates
gem "rexml", ">= 3.2.5"
gem "kramdown", ">= 2.3.1"
gem "nokogiri", ">= 1.11.0"

gem "github-pages", group: :jekyll_plugins
gem "kramdown-parser-gfm"

